//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMS.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權限等級 的當地語系化字串。
        /// </summary>
        public static string AccountLevel_Level {
            get {
                return ResourceManager.GetString("AccountLevel_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權限名稱 的當地語系化字串。
        /// </summary>
        public static string AccountLevel_LevelName {
            get {
                return ResourceManager.GetString("AccountLevel_LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccountLevelMgr 的當地語系化字串。
        /// </summary>
        public static string AccountLevelMgr {
            get {
                return ResourceManager.GetString("AccountLevelMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccountMgr 的當地語系化字串。
        /// </summary>
        public static string AccountMgr {
            get {
                return ResourceManager.GetString("AccountMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccountName 的當地語系化字串。
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccountNo 的當地語系化字串。
        /// </summary>
        public static string AccountNo {
            get {
                return ResourceManager.GetString("AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customer 的當地語系化字串。
        /// </summary>
        public static string BaseData_Customer {
            get {
                return ResourceManager.GetString("BaseData_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Expenses 的當地語系化字串。
        /// </summary>
        public static string BaseData_Expenses {
            get {
                return ResourceManager.GetString("BaseData_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FixedCost 的當地語系化字串。
        /// </summary>
        public static string BaseData_FixedCost {
            get {
                return ResourceManager.GetString("BaseData_FixedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Income 的當地語系化字串。
        /// </summary>
        public static string BaseData_Income {
            get {
                return ResourceManager.GetString("BaseData_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Med 的當地語系化字串。
        /// </summary>
        public static string BaseData_Med {
            get {
                return ResourceManager.GetString("BaseData_Med", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PigChange 的當地語系化字串。
        /// </summary>
        public static string BaseData_PigChange {
            get {
                return ResourceManager.GetString("BaseData_PigChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 基本資料表單 的當地語系化字串。
        /// </summary>
        public static string BaseSheet {
            get {
                return ResourceManager.GetString("BaseSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分類項目 的當地語系化字串。
        /// </summary>
        public static string CategoryMgr {
            get {
                return ResourceManager.GetString("CategoryMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CategorySubMgr 的當地語系化字串。
        /// </summary>
        public static string CategorySubMgr {
            get {
                return ResourceManager.GetString("CategorySubMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change Password 的當地語系化字串。
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add 的當地語系化字串。
        /// </summary>
        public static string Comm_Add {
            get {
                return ResourceManager.GetString("Comm_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Account 的當地語系化字串。
        /// </summary>
        public static string Comm_AddAccount {
            get {
                return ResourceManager.GetString("Comm_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BackToList 的當地語系化字串。
        /// </summary>
        public static string Comm_BackToList {
            get {
                return ResourceManager.GetString("Comm_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancek 的當地語系化字串。
        /// </summary>
        public static string Comm_Cancel {
            get {
                return ResourceManager.GetString("Comm_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        public static string Comm_Delete {
            get {
                return ResourceManager.GetString("Comm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Details 的當地語系化字串。
        /// </summary>
        public static string Comm_Details {
            get {
                return ResourceManager.GetString("Comm_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        public static string Comm_Edit {
            get {
                return ResourceManager.GetString("Comm_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter 的當地語系化字串。
        /// </summary>
        public static string Comm_Enter {
            get {
                return ResourceManager.GetString("Comm_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Learn more 的當地語系化字串。
        /// </summary>
        public static string Comm_LearnMore {
            get {
                return ResourceManager.GetString("Comm_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Print 的當地語系化字串。
        /// </summary>
        public static string Comm_Print {
            get {
                return ResourceManager.GetString("Comm_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        public static string Comm_Save {
            get {
                return ResourceManager.GetString("Comm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search 的當地語系化字串。
        /// </summary>
        public static string Comm_Search {
            get {
                return ResourceManager.GetString("Comm_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 View 的當地語系化字串。
        /// </summary>
        public static string Comm_View {
            get {
                return ResourceManager.GetString("Comm_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Kuo,TsungHan 的當地語系化字串。
        /// </summary>
        public static string Creater {
            get {
                return ResourceManager.GetString("Creater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Associative 的當地語系化字串。
        /// </summary>
        public static string DataAnalysis_Associative {
            get {
                return ResourceManager.GetString("DataAnalysis_Associative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Classification 的當地語系化字串。
        /// </summary>
        public static string DataAnalysis_Classification {
            get {
                return ResourceManager.GetString("DataAnalysis_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cluster 的當地語系化字串。
        /// </summary>
        public static string DataAnalysis_Cluster {
            get {
                return ResourceManager.GetString("DataAnalysis_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Regression 的當地語系化字串。
        /// </summary>
        public static string DataAnalysis_Regression {
            get {
                return ResourceManager.GetString("DataAnalysis_Regression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 none 的當地語系化字串。
        /// </summary>
        public static string Dropdown_Null {
            get {
                return ResourceManager.GetString("Dropdown_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abnormal 的當地語系化字串。
        /// </summary>
        public static string EnvironmentData_Abnormal {
            get {
                return ResourceManager.GetString("EnvironmentData_Abnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Humidity 的當地語系化字串。
        /// </summary>
        public static string EnvironmentData_Humidity {
            get {
                return ResourceManager.GetString("EnvironmentData_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image 的當地語系化字串。
        /// </summary>
        public static string EnvironmentData_Image {
            get {
                return ResourceManager.GetString("EnvironmentData_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Temperature 的當地語系化字串。
        /// </summary>
        public static string EnvironmentData_Temperature {
            get {
                return ResourceManager.GetString("EnvironmentData_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Barn 的當地語系化字串。
        /// </summary>
        public static string FarmData_Barn {
            get {
                return ResourceManager.GetString("FarmData_Barn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Base 的當地語系化字串。
        /// </summary>
        public static string FarmData_base {
            get {
                return ResourceManager.GetString("FarmData_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Land 的當地語系化字串。
        /// </summary>
        public static string FarmData_Land {
            get {
                return ResourceManager.GetString("FarmData_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 License 的當地語系化字串。
        /// </summary>
        public static string FarmData_License {
            get {
                return ResourceManager.GetString("FarmData_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Home 的當地語系化字串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        public static string LangSys {
            get {
                return ResourceManager.GetString("LangSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SingIn 的當地語系化字串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RemeberMe 的當地語系化字串。
        /// </summary>
        public static string Login_RemeberMe {
            get {
                return ResourceManager.GetString("Login_RemeberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SingOut 的當地語系化字串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BaseData 的當地語系化字串。
        /// </summary>
        public static string Management_BaseData {
            get {
                return ResourceManager.GetString("Management_BaseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EnvironmentData 的當地語系化字串。
        /// </summary>
        public static string Management_EnvironmentData {
            get {
                return ResourceManager.GetString("Management_EnvironmentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FarmData 的當地語系化字串。
        /// </summary>
        public static string Management_FarmData {
            get {
                return ResourceManager.GetString("Management_FarmData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Memo 的當地語系化字串。
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dashboard 的當地語系化字串。
        /// </summary>
        public static string MenuDashboard {
            get {
                return ResourceManager.GetString("MenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Home 的當地語系化字串。
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 豬隻管理 的當地語系化字串。
        /// </summary>
        public static string MenuPigM {
            get {
                return ResourceManager.GetString("MenuPigM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報表 的當地語系化字串。
        /// </summary>
        public static string MenuReport {
            get {
                return ResourceManager.GetString("MenuReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存 的當地語系化字串。
        /// </summary>
        public static string MenuStock {
            get {
                return ResourceManager.GetString("MenuStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System 的當地語系化字串。
        /// </summary>
        public static string MenuSys {
            get {
                return ResourceManager.GetString("MenuSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DataAnalysis 的當地語系化字串。
        /// </summary>
        public static string Model_DataAnalysis {
            get {
                return ResourceManager.GetString("Model_DataAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Management 的當地語系化字串。
        /// </summary>
        public static string Model_Management {
            get {
                return ResourceManager.GetString("Model_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Traceability 的當地語系化字串。
        /// </summary>
        public static string Model_Traceability {
            get {
                return ResourceManager.GetString("Model_Traceability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account or Password Error 的當地語系化字串。
        /// </summary>
        public static string Msg_LoginError {
            get {
                return ResourceManager.GetString("Msg_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PigFarm 的當地語系化字串。
        /// </summary>
        public static string PigFarm {
            get {
                return ResourceManager.GetString("PigFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose PigFarm 的當地語系化字串。
        /// </summary>
        public static string PigFarmChoose {
            get {
                return ResourceManager.GetString("PigFarmChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PigFarmMgr 的當地語系化字串。
        /// </summary>
        public static string PigFarmMgr {
            get {
                return ResourceManager.GetString("PigFarmMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 豬隻履歷管理 的當地語系化字串。
        /// </summary>
        public static string PigResumeM {
            get {
                return ResourceManager.GetString("PigResumeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 豬隻生產履歷 的當地語系化字串。
        /// </summary>
        public static string PigResumeMProduce {
            get {
                return ResourceManager.GetString("PigResumeMProduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PkgDate 的當地語系化字串。
        /// </summary>
        public static string PkgDate {
            get {
                return ResourceManager.GetString("PkgDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BigCut 的當地語系化字串。
        /// </summary>
        public static string Process_BigCut {
            get {
                return ResourceManager.GetString("Process_BigCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Butcher 的當地語系化字串。
        /// </summary>
        public static string Process_Butcher {
            get {
                return ResourceManager.GetString("Process_Butcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Package 的當地語系化字串。
        /// </summary>
        public static string Process_Package {
            get {
                return ResourceManager.GetString("Process_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SmallCut 的當地語系化字串。
        /// </summary>
        public static string Process_SmallCut {
            get {
                return ResourceManager.GetString("Process_SmallCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Environment 的當地語系化字串。
        /// </summary>
        public static string Produce_Environment {
            get {
                return ResourceManager.GetString("Produce_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Feed And Additive 的當地語系化字串。
        /// </summary>
        public static string Produce_FeedAndAdditive {
            get {
                return ResourceManager.GetString("Produce_FeedAndAdditive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Feeding And Batch 的當地語系化字串。
        /// </summary>
        public static string Produce_FeedingAndBatch {
            get {
                return ResourceManager.GetString("Produce_FeedingAndBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Health 的當地語系化字串。
        /// </summary>
        public static string Produce_Health {
            get {
                return ResourceManager.GetString("Produce_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Med 的當地語系化字串。
        /// </summary>
        public static string Produce_Med {
            get {
                return ResourceManager.GetString("Produce_Med", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Required 的當地語系化字串。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全場消毒紀錄表 的當地語系化字串。
        /// </summary>
        public static string SheetDisinfection {
            get {
                return ResourceManager.GetString("SheetDisinfection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統選單 的當地語系化字串。
        /// </summary>
        public static string SysMenu {
            get {
                return ResourceManager.GetString("SysMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Smart LiveStock 的當地語系化字串。
        /// </summary>
        public static string SysTitle {
            get {
                return ResourceManager.GetString("SysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Process 的當地語系化字串。
        /// </summary>
        public static string Traceability_Process {
            get {
                return ResourceManager.GetString("Traceability_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Produce 的當地語系化字串。
        /// </summary>
        public static string Traceability_Produce {
            get {
                return ResourceManager.GetString("Traceability_Produce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TraceCode 的當地語系化字串。
        /// </summary>
        public static string TraceCode {
            get {
                return ResourceManager.GetString("TraceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TraceCreate 的當地語系化字串。
        /// </summary>
        public static string TraceCreate {
            get {
                return ResourceManager.GetString("TraceCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TraceEdit 的當地語系化字串。
        /// </summary>
        public static string TraceEdit {
            get {
                return ResourceManager.GetString("TraceEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TraceNo 的當地語系化字串。
        /// </summary>
        public static string TraceNo {
            get {
                return ResourceManager.GetString("TraceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User 的當地語系化字串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User Setting 的當地語系化字串。
        /// </summary>
        public static string UserSetting {
            get {
                return ResourceManager.GetString("UserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Welcome 的當地語系化字串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WorkBasicMgr 的當地語系化字串。
        /// </summary>
        public static string WorkBasicMgr {
            get {
                return ResourceManager.GetString("WorkBasicMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WorkClass 的當地語系化字串。
        /// </summary>
        public static string WorkClass {
            get {
                return ResourceManager.GetString("WorkClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WorkCode 的當地語系化字串。
        /// </summary>
        public static string WorkCode {
            get {
                return ResourceManager.GetString("WorkCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WorkContent 的當地語系化字串。
        /// </summary>
        public static string WorkContent {
            get {
                return ResourceManager.GetString("WorkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WorkDate 的當地語系化字串。
        /// </summary>
        public static string WorkDate {
            get {
                return ResourceManager.GetString("WorkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WorkProcess 的當地語系化字串。
        /// </summary>
        public static string WorkProcess {
            get {
                return ResourceManager.GetString("WorkProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WorkType 的當地語系化字串。
        /// </summary>
        public static string WorkType {
            get {
                return ResourceManager.GetString("WorkType", resourceCulture);
            }
        }
    }
}
